apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pv1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zzzzzzzz
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/zzzzzzzz"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pv2"
