apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web
  name: web
spec:
  containers:
  - image: nginx:1.16.1
    name: web
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
