apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: td
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: td
status:
  loadBalancer: {}
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: td
  name: td
spec:
  replicas: 2
  selector:
    matchLabels:
      run: td
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: td
    spec:
      containers:
      - image: alstard/teamdemo
        name: td
        ports:
        - containerPort: 8080
        resources: {}
status: {}
